"""initial_schema

Revision ID: 5faa72b43b46
Revises: 
Create Date: 2025-12-17 11:08:05.649073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = '5faa72b43b46'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_learning_style', sa.String(length=50), nullable=True))
        batch_op.drop_column('notification_preferences')
        batch_op.drop_column('total_spent')
        batch_op.drop_column('profile_photo_url')
        batch_op.drop_column('total_sessions_completed')
        batch_op.drop_column('preferred_session_duration')
        batch_op.drop_column('preferred_language')

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
        batch_op.alter_column('category',
               existing_type=sa.VARCHAR(length=11),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.alter_column('is_active',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_subjects_category'))
        batch_op.drop_index(batch_op.f('ix_subjects_name'))
        batch_op.create_index(batch_op.f('ix_subjects_slug'), ['slug'], unique=True)
        batch_op.create_unique_constraint(None, ['name'])

    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.alter_column('file_type',
               existing_type=sa.VARCHAR(length=13),
               type_=sa.Enum('PROFILE_PHOTO', 'INTRO_VIDEO', 'CERTIFICATE', 'DOCUMENT', 'MESSAGE_ATTACHMENT', name='filetype'),
               existing_nullable=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    with op.batch_alter_table('uploaded_files', schema=None) as batch_op:
        batch_op.alter_column('file_type',
               existing_type=sa.Enum('PROFILE_PHOTO', 'INTRO_VIDEO', 'CERTIFICATE', 'DOCUMENT', 'MESSAGE_ATTACHMENT', name='filetype'),
               type_=sa.VARCHAR(length=13),
               existing_nullable=False)

    with op.batch_alter_table('subjects', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_index(batch_op.f('ix_subjects_slug'))
        batch_op.create_index(batch_op.f('ix_subjects_name'), ['name'], unique=1)
        batch_op.create_index(batch_op.f('ix_subjects_category'), ['category'], unique=False)
        batch_op.alter_column('is_active',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('category',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=11),
               nullable=False)
        batch_op.alter_column('description',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.alter_column('slug',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    with op.batch_alter_table('student_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preferred_language', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('preferred_session_duration', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('total_sessions_completed', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('profile_photo_url', sa.VARCHAR(length=500), nullable=True))
        batch_op.add_column(sa.Column('total_spent', sa.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('notification_preferences', sqlite.JSON(), nullable=True))
        batch_op.drop_column('preferred_learning_style')

    # ### end Alembic commands ###
